version: '3.9'

services:
  web:
    build: .
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - ConnectionStrings:FatpDatabase=Host=db;Username=postgres;Password=password
      - AppLogging:DefaultLogEventLevel=Information
      - AppLogging:OverrideLogEventLevel=Warning
      - GoogleAnalytics:MeasurementId=EndToEndTesting

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: password