global using Application.Commands;
global using FluentAssertions;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
global using Moq;
global using Tests.Utilities;
global using Xunit;
