name: Deploy project to Azure Function App
description: Deploy project to Azure Function App

inputs:
  dotnet_version:
    required: true
    type: string
    default: '6.0.x'
  working_directory:
    required: true
    type: string
    default: './Functions'
  az_tenant_id:
    required: true
    type: string
  az_subscription_id:
    required: true
    type: string
  az_client_id:
    required: true
    type: string
  az_client_secret:
    required: true
    type: string
  az_resource_group_name:
    required: true
    type: string
    
runs:
  using: composite
  
  steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup DotNet ${{ inputs.dotnet_version }} Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd './${{ inputs.working_directory }}'
        dotnet build --configuration Release --output ./output
        popd
        
    - name: Azure CLI Login
      uses: ./.github/actions/azure-login
      with:
        az_tenant_id: ${{ inputs.az_tenant_id }}
        az_subscription_id: ${{ inputs.az_subscription_id }}
        az_client_id: ${{ inputs.az_client_id }}
        az_client_secret: ${{ inputs.az_client_secret }}
      
    - name: Get Function App names from Resource Group
      shell: bash
      run: |
        RESOURCE_GROUP=${{ inputs.az_resource_group_name }}

        # Get all function apps in the resource group
        function_apps=$(az functionapp list --resource-group $RESOURCE_GROUP --query "[].name" -o tsv)
          
        if [ -z "$function_apps" ]; then
          echo "No Function Apps found in the resource group: $RESOURCE_GROUP."
        else
          echo "Function Apps found in the resource group: $RESOURCE_GROUP:"
          for app in $function_apps; do
            echo $app
          done
        # Optionally set the first function app name as an environment variable (if required)
          first_app=$(echo $function_apps | awk '{print $1}')
          echo "First Function App: $first_app"
          echo "FUNCTION_APP_NAME=$first_app" >> $GITHUB_ENV
        fi

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.FUNCTION_APP_NAME }}
        package: '${{ inputs.working_directory }}/output'
    