using Domain;
using Domain.Constants;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Infrastructure.EntityConfigurations;

public class LocalAuthorityDistrictConfiguration : IEntityTypeConfiguration<LocalAuthorityDistrict>
{
    public void Configure(EntityTypeBuilder<LocalAuthorityDistrict> builder)
    {
        builder.HasIndex(e => e.Code).IsUnique();
        builder.HasIndex(e => e.Name);
        builder
            .HasOne(e => e.Region)
            .WithMany(x => x.LocalAuthorityDistricts)
            .OnDelete(DeleteBehavior.NoAction);

        builder.HasData(
            new LocalAuthorityDistrict { Id = 1, Code = "E06000011", Name = "East Riding of Yorkshire", RegionId = Regions.Id.YorkshireandTheHumber, LocalAuthorityId = LocalAuthorities.Id.EastRidingOfYorkshire },
            new LocalAuthorityDistrict { Id = 2, Code = "E06000012", Name = "North East Lincolnshire", RegionId = Regions.Id.YorkshireandTheHumber, LocalAuthorityId = LocalAuthorities.Id.NorthEastLincolnshire },
            new LocalAuthorityDistrict { Id = 3, Code = "E06000013", Name = "North Lincolnshire", RegionId = Regions.Id.YorkshireandTheHumber, LocalAuthorityId = LocalAuthorities.Id.NorthLincolnshire },
            new LocalAuthorityDistrict { Id = 4, Code = "E06000014", Name = "York", RegionId = Regions.Id.YorkshireandTheHumber, LocalAuthorityId = LocalAuthorities.Id.York },
            new LocalAuthorityDistrict { Id = 5, Code = "E07000163", Name = "Craven", RegionId = Regions.Id.YorkshireandTheHumber, LocalAuthorityId = LocalAuthorities.Id.NorthYorkshire },
            new LocalAuthorityDistrict { Id = 6, Code = "E07000164", Name = "Hambleton", RegionId = Regions.Id.YorkshireandTheHumber, LocalAuthorityId = LocalAuthorities.Id.NorthYorkshire },
            new LocalAuthorityDistrict { Id = 7, Code = "E07000165", Name = "Harrogate", RegionId = Regions.Id.YorkshireandTheHumber, LocalAuthorityId = LocalAuthorities.Id.NorthYorkshire },
            new LocalAuthorityDistrict { Id = 8, Code = "E07000166", Name = "Richmondshire", RegionId = Regions.Id.YorkshireandTheHumber, LocalAuthorityId = LocalAuthorities.Id.NorthYorkshire },
            new LocalAuthorityDistrict { Id = 9, Code = "E07000167", Name = "Ryedale", RegionId = Regions.Id.YorkshireandTheHumber, LocalAuthorityId = LocalAuthorities.Id.NorthYorkshire },
            new LocalAuthorityDistrict { Id = 10, Code = "E07000168", Name = "Scarborough", RegionId = Regions.Id.YorkshireandTheHumber, LocalAuthorityId = LocalAuthorities.Id.NorthYorkshire },
            new LocalAuthorityDistrict { Id = 11, Code = "E07000169", Name = "Selby", RegionId = Regions.Id.YorkshireandTheHumber, LocalAuthorityId = LocalAuthorities.Id.NorthYorkshire },
            new LocalAuthorityDistrict { Id = 12, Code = "E08000016", Name = "Barnsley", RegionId = Regions.Id.YorkshireandTheHumber, LocalAuthorityId = LocalAuthorities.Id.Barnsley },
            new LocalAuthorityDistrict { Id = 13, Code = "E08000017", Name = "Doncaster", RegionId = Regions.Id.YorkshireandTheHumber, LocalAuthorityId = LocalAuthorities.Id.Doncaster },
            new LocalAuthorityDistrict { Id = 14, Code = "E08000018", Name = "Rotherham", RegionId = Regions.Id.YorkshireandTheHumber, LocalAuthorityId = LocalAuthorities.Id.Rotherham },
            new LocalAuthorityDistrict { Id = 15, Code = "E08000019", Name = "Sheffield", RegionId = Regions.Id.YorkshireandTheHumber, LocalAuthorityId = LocalAuthorities.Id.Sheffield },
            new LocalAuthorityDistrict { Id = 16, Code = "E08000032", Name = "Bradford", RegionId = Regions.Id.YorkshireandTheHumber, LocalAuthorityId = LocalAuthorities.Id.Bradford },
            new LocalAuthorityDistrict { Id = 17, Code = "E08000033", Name = "Calderdale", RegionId = Regions.Id.YorkshireandTheHumber, LocalAuthorityId = LocalAuthorities.Id.Calderdale },
            new LocalAuthorityDistrict { Id = 18, Code = "E08000034", Name = "Kirklees", RegionId = Regions.Id.YorkshireandTheHumber, LocalAuthorityId = LocalAuthorities.Id.Kirklees },
            new LocalAuthorityDistrict { Id = 19, Code = "E08000035", Name = "Leeds", RegionId = Regions.Id.YorkshireandTheHumber, LocalAuthorityId = LocalAuthorities.Id.Leeds },
            new LocalAuthorityDistrict { Id = 20, Code = "E08000036", Name = "Wakefield", RegionId = Regions.Id.YorkshireandTheHumber, LocalAuthorityId = LocalAuthorities.Id.Wakefield },
            new LocalAuthorityDistrict { Id = 21, Code = "E06000010", Name = "Kingston upon Hull, City of", RegionId = Regions.Id.YorkshireandTheHumber, LocalAuthorityId = LocalAuthorities.Id.KingstonUponHullCityOf },
            new LocalAuthorityDistrict { Id = 22, Code = "E06000019", Name = "Herefordshire, County of", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Herefordshire },
            new LocalAuthorityDistrict { Id = 23, Code = "E06000020", Name = "Telford and Wrekin", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.TelfordAndWrekin },
            new LocalAuthorityDistrict { Id = 24, Code = "E06000021", Name = "Stoke-on-Trent", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.StokeOnTrent },
            new LocalAuthorityDistrict { Id = 25, Code = "E06000051", Name = "Shropshire", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Shropshire },
            new LocalAuthorityDistrict { Id = 26, Code = "E07000192", Name = "Cannock Chase", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Staffordshire },
            new LocalAuthorityDistrict { Id = 27, Code = "E07000193", Name = "East Staffordshire", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Staffordshire },
            new LocalAuthorityDistrict { Id = 28, Code = "E07000194", Name = "Lichfield", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Staffordshire },
            new LocalAuthorityDistrict { Id = 29, Code = "E07000195", Name = "Newcastle-under-Lyme", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Staffordshire },
            new LocalAuthorityDistrict { Id = 30, Code = "E07000196", Name = "South Staffordshire", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Staffordshire },
            new LocalAuthorityDistrict { Id = 31, Code = "E07000197", Name = "Stafford", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Staffordshire },
            new LocalAuthorityDistrict { Id = 32, Code = "E07000198", Name = "Staffordshire Moorlands", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Staffordshire },
            new LocalAuthorityDistrict { Id = 33, Code = "E07000199", Name = "Tamworth", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Staffordshire },
            new LocalAuthorityDistrict { Id = 34, Code = "E07000218", Name = "North Warwickshire", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Warwickshire },
            new LocalAuthorityDistrict { Id = 35, Code = "E07000219", Name = "Nuneaton and Bedworth", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Warwickshire },
            new LocalAuthorityDistrict { Id = 36, Code = "E07000220", Name = "Rugby", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Warwickshire },
            new LocalAuthorityDistrict { Id = 37, Code = "E07000221", Name = "Stratford-on-Avon", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Warwickshire },
            new LocalAuthorityDistrict { Id = 38, Code = "E07000222", Name = "Warwick", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Warwickshire },
            new LocalAuthorityDistrict { Id = 39, Code = "E07000234", Name = "Bromsgrove", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Worcestershire },
            new LocalAuthorityDistrict { Id = 40, Code = "E07000235", Name = "Malvern Hills", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Worcestershire },
            new LocalAuthorityDistrict { Id = 41, Code = "E07000236", Name = "Redditch", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Worcestershire },
            new LocalAuthorityDistrict { Id = 42, Code = "E07000237", Name = "Worcester", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Worcestershire },
            new LocalAuthorityDistrict { Id = 43, Code = "E07000238", Name = "Wychavon", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Worcestershire },
            new LocalAuthorityDistrict { Id = 44, Code = "E07000239", Name = "Wyre Forest", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Worcestershire },
            new LocalAuthorityDistrict { Id = 45, Code = "E08000025", Name = "Birmingham", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Birmingham },
            new LocalAuthorityDistrict { Id = 46, Code = "E08000026", Name = "Coventry", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Coventry },
            new LocalAuthorityDistrict { Id = 47, Code = "E08000027", Name = "Dudley", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Dudley },
            new LocalAuthorityDistrict { Id = 48, Code = "E08000028", Name = "Sandwell", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Sandwell },
            new LocalAuthorityDistrict { Id = 49, Code = "E08000029", Name = "Solihull", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Solihull },
            new LocalAuthorityDistrict { Id = 50, Code = "E08000030", Name = "Walsall", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Walsall },
            new LocalAuthorityDistrict { Id = 51, Code = "E08000031", Name = "Wolverhampton", RegionId = Regions.Id.WestMidlands, LocalAuthorityId = LocalAuthorities.Id.Wolverhampton },
            new LocalAuthorityDistrict { Id = 52, Code = "E06000022", Name = "Bath and North East Somerset", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.BathAndNorthEastSomerset },
            new LocalAuthorityDistrict { Id = 53, Code = "E06000023", Name = "Bristol, City of", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.BristolCityOf },
            new LocalAuthorityDistrict { Id = 54, Code = "E06000024", Name = "North Somerset", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.NorthSomerset },
            new LocalAuthorityDistrict { Id = 55, Code = "E06000025", Name = "South Gloucestershire", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.SouthGloucestershire },
            new LocalAuthorityDistrict { Id = 56, Code = "E06000026", Name = "Plymouth", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Plymouth },
            new LocalAuthorityDistrict { Id = 57, Code = "E06000027", Name = "Torbay", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Torbay },
            new LocalAuthorityDistrict { Id = 58, Code = "E06000030", Name = "Swindon", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Swindon },
            new LocalAuthorityDistrict { Id = 59, Code = "E06000052", Name = "Cornwall", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Cornwall },
            new LocalAuthorityDistrict { Id = 60, Code = "E06000053", Name = "Isles of Scilly", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.IslesOfScilly },
            new LocalAuthorityDistrict { Id = 61, Code = "E06000054", Name = "Wiltshire", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Wiltshire },
            new LocalAuthorityDistrict { Id = 62, Code = "E06000058", Name = "Bournemouth, Christchurch and Poole", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.BournemouthChristchurchAndPoole },
            new LocalAuthorityDistrict { Id = 63, Code = "E06000059", Name = "Dorset", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Dorset },
            new LocalAuthorityDistrict { Id = 64, Code = "E07000040", Name = "East Devon", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Devon },
            new LocalAuthorityDistrict { Id = 65, Code = "E07000041", Name = "Exeter", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Devon },
            new LocalAuthorityDistrict { Id = 66, Code = "E07000042", Name = "Mid Devon", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Devon },
            new LocalAuthorityDistrict { Id = 67, Code = "E07000043", Name = "North Devon", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Devon },
            new LocalAuthorityDistrict { Id = 68, Code = "E07000044", Name = "South Hams", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Devon },
            new LocalAuthorityDistrict { Id = 69, Code = "E07000045", Name = "Teignbridge", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Devon },
            new LocalAuthorityDistrict { Id = 70, Code = "E07000046", Name = "Torridge", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Devon },
            new LocalAuthorityDistrict { Id = 71, Code = "E07000047", Name = "West Devon", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Devon },
            new LocalAuthorityDistrict { Id = 72, Code = "E07000078", Name = "Cheltenham", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Gloucestershire },
            new LocalAuthorityDistrict { Id = 73, Code = "E07000079", Name = "Cotswold", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Gloucestershire },
            new LocalAuthorityDistrict { Id = 74, Code = "E07000080", Name = "Forest of Dean", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Gloucestershire },
            new LocalAuthorityDistrict { Id = 75, Code = "E07000081", Name = "Gloucester", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Gloucestershire },
            new LocalAuthorityDistrict { Id = 76, Code = "E07000082", Name = "Stroud", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Gloucestershire },
            new LocalAuthorityDistrict { Id = 77, Code = "E07000083", Name = "Tewkesbury", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Gloucestershire },
            new LocalAuthorityDistrict { Id = 78, Code = "E07000187", Name = "Mendip", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Somerset },
            new LocalAuthorityDistrict { Id = 79, Code = "E07000188", Name = "Sedgemoor", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Somerset },
            new LocalAuthorityDistrict { Id = 80, Code = "E07000189", Name = "South Somerset", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Somerset },
            new LocalAuthorityDistrict { Id = 81, Code = "E07000246", Name = "Somerset West and Taunton", RegionId = Regions.Id.SouthWest, LocalAuthorityId = LocalAuthorities.Id.Somerset },
            new LocalAuthorityDistrict { Id = 82, Code = "E07000181", Name = "West Oxfordshire", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Oxfordshire },
            new LocalAuthorityDistrict { Id = 83, Code = "E07000207", Name = "Elmbridge", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Surrey },
            new LocalAuthorityDistrict { Id = 84, Code = "E07000208", Name = "Epsom and Ewell", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Surrey },
            new LocalAuthorityDistrict { Id = 85, Code = "E07000209", Name = "Guildford", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Surrey },
            new LocalAuthorityDistrict { Id = 86, Code = "E07000210", Name = "Mole Valley", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Surrey },
            new LocalAuthorityDistrict { Id = 87, Code = "E07000211", Name = "Reigate and Banstead", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Surrey },
            new LocalAuthorityDistrict { Id = 88, Code = "E07000212", Name = "Runnymede", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Surrey },
            new LocalAuthorityDistrict { Id = 89, Code = "E06000035", Name = "Medway", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Medway },
            new LocalAuthorityDistrict { Id = 90, Code = "E07000213", Name = "Spelthorne", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Surrey },
            new LocalAuthorityDistrict { Id = 91, Code = "E06000036", Name = "Bracknell Forest", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.BracknellForest },
            new LocalAuthorityDistrict { Id = 92, Code = "E07000214", Name = "Surrey Heath", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Surrey },
            new LocalAuthorityDistrict { Id = 93, Code = "E06000037", Name = "West Berkshire", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.WestBerkshire },
            new LocalAuthorityDistrict { Id = 94, Code = "E07000215", Name = "Tandridge", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Surrey },
            new LocalAuthorityDistrict { Id = 95, Code = "E06000038", Name = "Reading", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Reading },
            new LocalAuthorityDistrict { Id = 96, Code = "E07000216", Name = "Waverley", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Surrey },
            new LocalAuthorityDistrict { Id = 97, Code = "E06000039", Name = "Slough", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Slough },
            new LocalAuthorityDistrict { Id = 98, Code = "E07000217", Name = "Woking", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Surrey },
            new LocalAuthorityDistrict { Id = 99, Code = "E06000040", Name = "Windsor and Maidenhead", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.WindsorAndMaidenhead },
            new LocalAuthorityDistrict { Id = 100, Code = "E07000223", Name = "Adur", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.WestSussex },
            new LocalAuthorityDistrict { Id = 101, Code = "E06000041", Name = "Wokingham", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Wokingham },
            new LocalAuthorityDistrict { Id = 102, Code = "E07000224", Name = "Arun", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.WestSussex },
            new LocalAuthorityDistrict { Id = 103, Code = "E06000042", Name = "Milton Keynes", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.MiltonKeynes },
            new LocalAuthorityDistrict { Id = 104, Code = "E07000225", Name = "Chichester", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.WestSussex },
            new LocalAuthorityDistrict { Id = 105, Code = "E06000043", Name = "Brighton and Hove", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.BrightonAndHove },
            new LocalAuthorityDistrict { Id = 106, Code = "E07000226", Name = "Crawley", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.WestSussex },
            new LocalAuthorityDistrict { Id = 107, Code = "E06000044", Name = "Portsmouth", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Portsmouth },
            new LocalAuthorityDistrict { Id = 108, Code = "E07000227", Name = "Horsham", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.WestSussex },
            new LocalAuthorityDistrict { Id = 109, Code = "E06000045", Name = "Southampton", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Southampton },
            new LocalAuthorityDistrict { Id = 110, Code = "E07000228", Name = "Mid Sussex", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.WestSussex },
            new LocalAuthorityDistrict { Id = 111, Code = "E06000046", Name = "Isle of Wight", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.IsleOfWight },
            new LocalAuthorityDistrict { Id = 112, Code = "E07000229", Name = "Worthing", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.WestSussex },
            new LocalAuthorityDistrict { Id = 113, Code = "E06000060", Name = "Buckinghamshire", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Buckinghamshire },
            new LocalAuthorityDistrict { Id = 114, Code = "E07000061", Name = "Eastbourne", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.EastSussex },
            new LocalAuthorityDistrict { Id = 115, Code = "E07000062", Name = "Hastings", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.EastSussex },
            new LocalAuthorityDistrict { Id = 116, Code = "E07000063", Name = "Lewes", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.EastSussex },
            new LocalAuthorityDistrict { Id = 117, Code = "E07000064", Name = "Rother", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.EastSussex },
            new LocalAuthorityDistrict { Id = 118, Code = "E07000065", Name = "Wealden", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.EastSussex },
            new LocalAuthorityDistrict { Id = 119, Code = "E07000084", Name = "Basingstoke and Deane", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Hampshire },
            new LocalAuthorityDistrict { Id = 120, Code = "E07000085", Name = "East Hampshire", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Hampshire },
            new LocalAuthorityDistrict { Id = 121, Code = "E07000086", Name = "Eastleigh", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Hampshire },
            new LocalAuthorityDistrict { Id = 122, Code = "E07000087", Name = "Fareham", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Hampshire },
            new LocalAuthorityDistrict { Id = 123, Code = "E07000088", Name = "Gosport", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Hampshire },
            new LocalAuthorityDistrict { Id = 124, Code = "E07000089", Name = "Hart", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Hampshire },
            new LocalAuthorityDistrict { Id = 125, Code = "E07000090", Name = "Havant", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Hampshire },
            new LocalAuthorityDistrict { Id = 126, Code = "E07000091", Name = "New Forest", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Hampshire },
            new LocalAuthorityDistrict { Id = 127, Code = "E07000092", Name = "Rushmoor", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Hampshire },
            new LocalAuthorityDistrict { Id = 128, Code = "E07000093", Name = "Test Valley", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Hampshire },
            new LocalAuthorityDistrict { Id = 129, Code = "E07000094", Name = "Winchester", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Hampshire },
            new LocalAuthorityDistrict { Id = 130, Code = "E07000105", Name = "Ashford", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Kent },
            new LocalAuthorityDistrict { Id = 131, Code = "E07000106", Name = "Canterbury", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Kent },
            new LocalAuthorityDistrict { Id = 132, Code = "E07000107", Name = "Dartford", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Kent },
            new LocalAuthorityDistrict { Id = 133, Code = "E07000108", Name = "Dover", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Kent },
            new LocalAuthorityDistrict { Id = 134, Code = "E07000109", Name = "Gravesham", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Kent },
            new LocalAuthorityDistrict { Id = 135, Code = "E07000110", Name = "Maidstone", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Kent },
            new LocalAuthorityDistrict { Id = 136, Code = "E07000111", Name = "Sevenoaks", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Kent },
            new LocalAuthorityDistrict { Id = 137, Code = "E07000112", Name = "Folkestone and Hythe", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Kent },
            new LocalAuthorityDistrict { Id = 138, Code = "E07000113", Name = "Swale", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Kent },
            new LocalAuthorityDistrict { Id = 139, Code = "E07000114", Name = "Thanet", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Kent },
            new LocalAuthorityDistrict { Id = 140, Code = "E07000115", Name = "Tonbridge and Malling", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Kent },
            new LocalAuthorityDistrict { Id = 141, Code = "E07000116", Name = "Tunbridge Wells", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Kent },
            new LocalAuthorityDistrict { Id = 142, Code = "E07000177", Name = "Cherwell", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Oxfordshire },
            new LocalAuthorityDistrict { Id = 143, Code = "E07000178", Name = "Oxford", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Oxfordshire },
            new LocalAuthorityDistrict { Id = 144, Code = "E07000179", Name = "South Oxfordshire", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Oxfordshire },
            new LocalAuthorityDistrict { Id = 145, Code = "E07000180", Name = "Vale of White Horse", RegionId = Regions.Id.SouthEast, LocalAuthorityId = LocalAuthorities.Id.Oxfordshire },
            new LocalAuthorityDistrict { Id = 146, Code = "E06000006", Name = "Halton", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Halton },
            new LocalAuthorityDistrict { Id = 147, Code = "E06000007", Name = "Warrington", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Warrington },
            new LocalAuthorityDistrict { Id = 148, Code = "E06000008", Name = "Blackburn with Darwen", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.BlackburnWithDarwen },
            new LocalAuthorityDistrict { Id = 149, Code = "E06000009", Name = "Blackpool", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Blackpool },
            new LocalAuthorityDistrict { Id = 150, Code = "E06000049", Name = "Cheshire East", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.CheshireEast },
            new LocalAuthorityDistrict { Id = 151, Code = "E06000050", Name = "Cheshire West and Chester", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.CheshireWestAndChester },
            new LocalAuthorityDistrict { Id = 152, Code = "E07000026", Name = "Allerdale", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Cumbria },
            new LocalAuthorityDistrict { Id = 153, Code = "E07000027", Name = "Barrow-in-Furness", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Cumbria },
            new LocalAuthorityDistrict { Id = 154, Code = "E07000028", Name = "Carlisle", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Cumbria },
            new LocalAuthorityDistrict { Id = 155, Code = "E07000029", Name = "Copeland", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Cumbria },
            new LocalAuthorityDistrict { Id = 156, Code = "E07000030", Name = "Eden", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Cumbria },
            new LocalAuthorityDistrict { Id = 157, Code = "E07000031", Name = "South Lakeland", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Cumbria },
            new LocalAuthorityDistrict { Id = 158, Code = "E07000117", Name = "Burnley", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Lancashire },
            new LocalAuthorityDistrict { Id = 159, Code = "E07000118", Name = "Chorley", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Lancashire },
            new LocalAuthorityDistrict { Id = 160, Code = "E07000119", Name = "Fylde", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Lancashire },
            new LocalAuthorityDistrict { Id = 161, Code = "E07000120", Name = "Hyndburn", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Lancashire },
            new LocalAuthorityDistrict { Id = 162, Code = "E07000121", Name = "Lancaster", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Lancashire },
            new LocalAuthorityDistrict { Id = 163, Code = "E07000122", Name = "Pendle", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Lancashire },
            new LocalAuthorityDistrict { Id = 164, Code = "E07000123", Name = "Preston", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Lancashire },
            new LocalAuthorityDistrict { Id = 165, Code = "E07000124", Name = "Ribble Valley", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Lancashire },
            new LocalAuthorityDistrict { Id = 166, Code = "E07000125", Name = "Rossendale", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Lancashire },
            new LocalAuthorityDistrict { Id = 167, Code = "E07000126", Name = "South Ribble", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Lancashire },
            new LocalAuthorityDistrict { Id = 168, Code = "E07000127", Name = "West Lancashire", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Lancashire },
            new LocalAuthorityDistrict { Id = 169, Code = "E07000128", Name = "Wyre", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Lancashire },
            new LocalAuthorityDistrict { Id = 170, Code = "E08000001", Name = "Bolton", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Bolton },
            new LocalAuthorityDistrict { Id = 171, Code = "E08000002", Name = "Bury", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Bury },
            new LocalAuthorityDistrict { Id = 172, Code = "E08000003", Name = "Manchester", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Manchester },
            new LocalAuthorityDistrict { Id = 173, Code = "E08000004", Name = "Oldham", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Oldham },
            new LocalAuthorityDistrict { Id = 174, Code = "E08000005", Name = "Rochdale", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Rochdale },
            new LocalAuthorityDistrict { Id = 175, Code = "E08000006", Name = "Salford", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Salford },
            new LocalAuthorityDistrict { Id = 176, Code = "E08000007", Name = "Stockport", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Stockport },
            new LocalAuthorityDistrict { Id = 177, Code = "E08000008", Name = "Tameside", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Tameside },
            new LocalAuthorityDistrict { Id = 178, Code = "E08000009", Name = "Trafford", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Trafford },
            new LocalAuthorityDistrict { Id = 179, Code = "E08000010", Name = "Wigan", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Wigan },
            new LocalAuthorityDistrict { Id = 180, Code = "E08000011", Name = "Knowsley", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Knowsley },
            new LocalAuthorityDistrict { Id = 181, Code = "E08000012", Name = "Liverpool", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Liverpool },
            new LocalAuthorityDistrict { Id = 182, Code = "E08000013", Name = "St. Helens", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.StHelens },
            new LocalAuthorityDistrict { Id = 183, Code = "E08000014", Name = "Sefton", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Sefton },
            new LocalAuthorityDistrict { Id = 184, Code = "E08000015", Name = "Wirral", RegionId = Regions.Id.NorthWest, LocalAuthorityId = LocalAuthorities.Id.Wirral },
            new LocalAuthorityDistrict { Id = 185, Code = "E06000001", Name = "Hartlepool", RegionId = Regions.Id.NorthEast, LocalAuthorityId = LocalAuthorities.Id.Hartlepool },
            new LocalAuthorityDistrict { Id = 186, Code = "E06000002", Name = "Middlesbrough", RegionId = Regions.Id.NorthEast, LocalAuthorityId = LocalAuthorities.Id.Middlesbrough },
            new LocalAuthorityDistrict { Id = 187, Code = "E06000003", Name = "Redcar and Cleveland", RegionId = Regions.Id.NorthEast, LocalAuthorityId = LocalAuthorities.Id.RedcarAndCleveland },
            new LocalAuthorityDistrict { Id = 188, Code = "E06000004", Name = "Stockton-on-Tees", RegionId = Regions.Id.NorthEast, LocalAuthorityId = LocalAuthorities.Id.StocktonOnTees },
            new LocalAuthorityDistrict { Id = 189, Code = "E06000005", Name = "Darlington", RegionId = Regions.Id.NorthEast, LocalAuthorityId = LocalAuthorities.Id.Darlington },
            new LocalAuthorityDistrict { Id = 190, Code = "E06000047", Name = "County Durham", RegionId = Regions.Id.NorthEast, LocalAuthorityId = LocalAuthorities.Id.Durham },
            new LocalAuthorityDistrict { Id = 191, Code = "E06000057", Name = "Northumberland", RegionId = Regions.Id.NorthEast, LocalAuthorityId = LocalAuthorities.Id.Northumberland },
            new LocalAuthorityDistrict { Id = 192, Code = "E08000021", Name = "Newcastle upon Tyne", RegionId = Regions.Id.NorthEast, LocalAuthorityId = LocalAuthorities.Id.NewcastleUponTyne },
            new LocalAuthorityDistrict { Id = 193, Code = "E08000022", Name = "North Tyneside", RegionId = Regions.Id.NorthEast, LocalAuthorityId = LocalAuthorities.Id.NorthTyneside },
            new LocalAuthorityDistrict { Id = 194, Code = "E08000023", Name = "South Tyneside", RegionId = Regions.Id.NorthEast, LocalAuthorityId = LocalAuthorities.Id.SouthTyneside },
            new LocalAuthorityDistrict { Id = 195, Code = "E08000024", Name = "Sunderland", RegionId = Regions.Id.NorthEast, LocalAuthorityId = LocalAuthorities.Id.Sunderland },
            new LocalAuthorityDistrict { Id = 196, Code = "E08000037", Name = "Gateshead", RegionId = Regions.Id.NorthEast, LocalAuthorityId = LocalAuthorities.Id.Gateshead },
            new LocalAuthorityDistrict { Id = 197, Code = "E09000027", Name = "Richmond upon Thames", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.RichmondUponThames },
            new LocalAuthorityDistrict { Id = 198, Code = "E09000028", Name = "Southwark", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Southwark },
            new LocalAuthorityDistrict { Id = 199, Code = "E09000029", Name = "Sutton", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Sutton },
            new LocalAuthorityDistrict { Id = 200, Code = "E09000030", Name = "Tower Hamlets", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.TowerHamlets },
            new LocalAuthorityDistrict { Id = 201, Code = "E09000031", Name = "Waltham Forest", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.WalthamForest },
            new LocalAuthorityDistrict { Id = 202, Code = "E09000032", Name = "Wandsworth", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Wandsworth },
            new LocalAuthorityDistrict { Id = 203, Code = "E09000033", Name = "Westminster", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Westminster },
            new LocalAuthorityDistrict { Id = 204, Code = "E09000001", Name = "City of London", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.CityOfLondon },
            new LocalAuthorityDistrict { Id = 205, Code = "E09000002", Name = "Barking and Dagenham", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.BarkingAndDagenham },
            new LocalAuthorityDistrict { Id = 206, Code = "E09000003", Name = "Barnet", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Barnet },
            new LocalAuthorityDistrict { Id = 207, Code = "E09000004", Name = "Bexley", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Bexley },
            new LocalAuthorityDistrict { Id = 208, Code = "E09000005", Name = "Brent", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Brent },
            new LocalAuthorityDistrict { Id = 209, Code = "E09000006", Name = "Bromley", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Bromley },
            new LocalAuthorityDistrict { Id = 210, Code = "E09000007", Name = "Camden", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Camden },
            new LocalAuthorityDistrict { Id = 211, Code = "E09000008", Name = "Croydon", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Croydon },
            new LocalAuthorityDistrict { Id = 212, Code = "E09000009", Name = "Ealing", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Ealing },
            new LocalAuthorityDistrict { Id = 213, Code = "E09000010", Name = "Enfield", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Enfield },
            new LocalAuthorityDistrict { Id = 214, Code = "E09000011", Name = "Greenwich", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Greenwich },
            new LocalAuthorityDistrict { Id = 215, Code = "E09000012", Name = "Hackney", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Hackney },
            new LocalAuthorityDistrict { Id = 216, Code = "E09000013", Name = "Hammersmith and Fulham", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.HammersmithAndFulham },
            new LocalAuthorityDistrict { Id = 217, Code = "E09000014", Name = "Haringey", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Haringey },
            new LocalAuthorityDistrict { Id = 218, Code = "E09000015", Name = "Harrow", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Harrow },
            new LocalAuthorityDistrict { Id = 219, Code = "E09000016", Name = "Havering", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Havering },
            new LocalAuthorityDistrict { Id = 220, Code = "E09000017", Name = "Hillingdon", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Hillingdon },
            new LocalAuthorityDistrict { Id = 221, Code = "E09000018", Name = "Hounslow", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Hounslow },
            new LocalAuthorityDistrict { Id = 222, Code = "E09000019", Name = "Islington", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Islington },
            new LocalAuthorityDistrict { Id = 223, Code = "E09000020", Name = "Kensington and Chelsea", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.KensingtonAndChelsea },
            new LocalAuthorityDistrict { Id = 224, Code = "E09000021", Name = "Kingston upon Thames", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.KingstonUponThames },
            new LocalAuthorityDistrict { Id = 225, Code = "E09000022", Name = "Lambeth", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Lambeth },
            new LocalAuthorityDistrict { Id = 226, Code = "E09000023", Name = "Lewisham", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Lewisham },
            new LocalAuthorityDistrict { Id = 227, Code = "E09000024", Name = "Merton", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Merton },
            new LocalAuthorityDistrict { Id = 228, Code = "E09000025", Name = "Newham", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Newham },
            new LocalAuthorityDistrict { Id = 229, Code = "E09000026", Name = "Redbridge", RegionId = Regions.Id.London, LocalAuthorityId = LocalAuthorities.Id.Redbridge },
            new LocalAuthorityDistrict { Id = 230, Code = "E06000031", Name = "Peterborough", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Peterborough },
            new LocalAuthorityDistrict { Id = 231, Code = "E06000032", Name = "Luton", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Luton },
            new LocalAuthorityDistrict { Id = 232, Code = "E06000033", Name = "Southend-on-Sea", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.SouthendOnSea },
            new LocalAuthorityDistrict { Id = 233, Code = "E06000034", Name = "Thurrock", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Thurrock },
            new LocalAuthorityDistrict { Id = 234, Code = "E06000055", Name = "Bedford", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Bedford },
            new LocalAuthorityDistrict { Id = 235, Code = "E06000056", Name = "Central Bedfordshire", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.CentralBedfordshire },
            new LocalAuthorityDistrict { Id = 236, Code = "E07000008", Name = "Cambridge", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Cambridgeshire },
            new LocalAuthorityDistrict { Id = 237, Code = "E07000009", Name = "East Cambridgeshire", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Cambridgeshire },
            new LocalAuthorityDistrict { Id = 238, Code = "E07000010", Name = "Fenland", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Cambridgeshire },
            new LocalAuthorityDistrict { Id = 239, Code = "E07000011", Name = "Huntingdonshire", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Cambridgeshire },
            new LocalAuthorityDistrict { Id = 240, Code = "E07000012", Name = "South Cambridgeshire", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Cambridgeshire },
            new LocalAuthorityDistrict { Id = 241, Code = "E07000066", Name = "Basildon", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Essex },
            new LocalAuthorityDistrict { Id = 242, Code = "E07000067", Name = "Braintree", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Essex },
            new LocalAuthorityDistrict { Id = 243, Code = "E07000068", Name = "Brentwood", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Essex },
            new LocalAuthorityDistrict { Id = 244, Code = "E07000069", Name = "Castle Point", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Essex },
            new LocalAuthorityDistrict { Id = 245, Code = "E07000070", Name = "Chelmsford", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Essex },
            new LocalAuthorityDistrict { Id = 246, Code = "E07000071", Name = "Colchester", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Essex },
            new LocalAuthorityDistrict { Id = 247, Code = "E07000072", Name = "Epping Forest", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Essex },
            new LocalAuthorityDistrict { Id = 248, Code = "E07000073", Name = "Harlow", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Essex },
            new LocalAuthorityDistrict { Id = 249, Code = "E07000074", Name = "Maldon", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Essex },
            new LocalAuthorityDistrict { Id = 250, Code = "E07000075", Name = "Rochford", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Essex },
            new LocalAuthorityDistrict { Id = 251, Code = "E07000076", Name = "Tendring", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Essex },
            new LocalAuthorityDistrict { Id = 252, Code = "E07000077", Name = "Uttlesford", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Essex },
            new LocalAuthorityDistrict { Id = 253, Code = "E07000095", Name = "Broxbourne", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Hertfordshire },
            new LocalAuthorityDistrict { Id = 254, Code = "E07000096", Name = "Dacorum", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Hertfordshire },
            new LocalAuthorityDistrict { Id = 255, Code = "E07000098", Name = "Hertsmere", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Hertfordshire },
            new LocalAuthorityDistrict { Id = 256, Code = "E07000099", Name = "North Hertfordshire", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Hertfordshire },
            new LocalAuthorityDistrict { Id = 257, Code = "E07000102", Name = "Three Rivers", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Hertfordshire },
            new LocalAuthorityDistrict { Id = 258, Code = "E07000103", Name = "Watford", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Hertfordshire },
            new LocalAuthorityDistrict { Id = 259, Code = "E07000143", Name = "Breckland", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Norfolk },
            new LocalAuthorityDistrict { Id = 260, Code = "E07000144", Name = "Broadland", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Norfolk },
            new LocalAuthorityDistrict { Id = 261, Code = "E07000145", Name = "Great Yarmouth", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Norfolk },
            new LocalAuthorityDistrict { Id = 262, Code = "E07000146", Name = "King's Lynn and West Norfolk", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Norfolk },
            new LocalAuthorityDistrict { Id = 263, Code = "E07000147", Name = "North Norfolk", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Norfolk },
            new LocalAuthorityDistrict { Id = 264, Code = "E07000148", Name = "Norwich", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Norfolk },
            new LocalAuthorityDistrict { Id = 265, Code = "E07000149", Name = "South Norfolk", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Norfolk },
            new LocalAuthorityDistrict { Id = 266, Code = "E07000200", Name = "Babergh", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Suffolk },
            new LocalAuthorityDistrict { Id = 267, Code = "E07000202", Name = "Ipswich", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Suffolk },
            new LocalAuthorityDistrict { Id = 268, Code = "E07000203", Name = "Mid Suffolk", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Suffolk },
            new LocalAuthorityDistrict { Id = 269, Code = "E07000240", Name = "St Albans", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Hertfordshire },
            new LocalAuthorityDistrict { Id = 270, Code = "E07000241", Name = "Welwyn Hatfield", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Hertfordshire },
            new LocalAuthorityDistrict { Id = 271, Code = "E07000242", Name = "East Hertfordshire", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Hertfordshire },
            new LocalAuthorityDistrict { Id = 272, Code = "E07000243", Name = "Stevenage", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Hertfordshire },
            new LocalAuthorityDistrict { Id = 273, Code = "E07000244", Name = "East Suffolk", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Suffolk },
            new LocalAuthorityDistrict { Id = 274, Code = "E07000245", Name = "West Suffolk", RegionId = Regions.Id.EastofEngland, LocalAuthorityId = LocalAuthorities.Id.Suffolk },
            new LocalAuthorityDistrict { Id = 275, Code = "E06000015", Name = "Derby", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Derby },
            new LocalAuthorityDistrict { Id = 276, Code = "E06000016", Name = "Leicester", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Leicester },
            new LocalAuthorityDistrict { Id = 277, Code = "E06000017", Name = "Rutland", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Rutland },
            new LocalAuthorityDistrict { Id = 278, Code = "E06000018", Name = "Nottingham", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Nottingham },
            new LocalAuthorityDistrict { Id = 279, Code = "E06000061", Name = "North Northamptonshire", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.NorthNorthamptonshire },
            new LocalAuthorityDistrict { Id = 280, Code = "E06000062", Name = "West Northamptonshire", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.WestNorthamptonshire },
            new LocalAuthorityDistrict { Id = 281, Code = "E07000032", Name = "Amber Valley", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Derbyshire },
            new LocalAuthorityDistrict { Id = 282, Code = "E07000033", Name = "Bolsover", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Derbyshire },
            new LocalAuthorityDistrict { Id = 283, Code = "E07000034", Name = "Chesterfield", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Derbyshire },
            new LocalAuthorityDistrict { Id = 284, Code = "E07000035", Name = "Derbyshire Dales", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Derbyshire },
            new LocalAuthorityDistrict { Id = 285, Code = "E07000036", Name = "Erewash", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Derbyshire },
            new LocalAuthorityDistrict { Id = 286, Code = "E07000037", Name = "High Peak", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Derbyshire },
            new LocalAuthorityDistrict { Id = 287, Code = "E07000038", Name = "North East Derbyshire", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Derbyshire },
            new LocalAuthorityDistrict { Id = 288, Code = "E07000039", Name = "South Derbyshire", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Derbyshire },
            new LocalAuthorityDistrict { Id = 289, Code = "E07000129", Name = "Blaby", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Leicestershire },
            new LocalAuthorityDistrict { Id = 290, Code = "E07000130", Name = "Charnwood", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Leicestershire },
            new LocalAuthorityDistrict { Id = 291, Code = "E07000131", Name = "Harborough", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Leicestershire },
            new LocalAuthorityDistrict { Id = 292, Code = "E07000132", Name = "Hinckley and Bosworth", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Leicestershire },
            new LocalAuthorityDistrict { Id = 293, Code = "E07000133", Name = "Melton", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Leicestershire },
            new LocalAuthorityDistrict { Id = 294, Code = "E07000134", Name = "North West Leicestershire", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Leicestershire },
            new LocalAuthorityDistrict { Id = 295, Code = "E07000135", Name = "Oadby and Wigston", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Leicestershire },
            new LocalAuthorityDistrict { Id = 296, Code = "E07000136", Name = "Boston", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Lincolnshire },
            new LocalAuthorityDistrict { Id = 297, Code = "E07000137", Name = "East Lindsey", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Lincolnshire },
            new LocalAuthorityDistrict { Id = 298, Code = "E07000138", Name = "Lincoln", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Lincolnshire },
            new LocalAuthorityDistrict { Id = 299, Code = "E07000139", Name = "North Kesteven", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Lincolnshire },
            new LocalAuthorityDistrict { Id = 300, Code = "E07000140", Name = "South Holland", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Lincolnshire },
            new LocalAuthorityDistrict { Id = 301, Code = "E07000141", Name = "South Kesteven", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Lincolnshire },
            new LocalAuthorityDistrict { Id = 302, Code = "E07000142", Name = "West Lindsey", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Lincolnshire },
            new LocalAuthorityDistrict { Id = 303, Code = "E07000170", Name = "Ashfield", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Nottinghamshire },
            new LocalAuthorityDistrict { Id = 304, Code = "E07000171", Name = "Bassetlaw", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Nottinghamshire },
            new LocalAuthorityDistrict { Id = 305, Code = "E07000172", Name = "Broxtowe", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Nottinghamshire },
            new LocalAuthorityDistrict { Id = 306, Code = "E07000173", Name = "Gedling", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Nottinghamshire },
            new LocalAuthorityDistrict { Id = 307, Code = "E07000174", Name = "Mansfield", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Nottinghamshire },
            new LocalAuthorityDistrict { Id = 308, Code = "E07000175", Name = "Newark and Sherwood", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Nottinghamshire },
            new LocalAuthorityDistrict { Id = 309, Code = "E07000176", Name = "Rushcliffe", RegionId = Regions.Id.EastMidlands, LocalAuthorityId = LocalAuthorities.Id.Nottinghamshire }
        );
    }
}