using Domain;
using Domain.Constants;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Infrastructure.EntityConfigurations;

public class LocalAuthorityConfiguration : IEntityTypeConfiguration<LocalAuthority>
{
    public void Configure(EntityTypeBuilder<LocalAuthority> builder)
    {
        builder.HasIndex(e => e.Code);
        builder.HasIndex(e => e.Name);

        builder.HasData(
            new LocalAuthority { Id = LocalAuthorities.Id.BarkingAndDagenham, Code = "E09000002", Name = "Barking and Dagenham", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Barnet, Code = "E09000003", Name = "Barnet", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Barnsley, Code = "E08000016", Name = "Barnsley", RegionId = Regions.Id.YorkshireandTheHumber },
            new LocalAuthority { Id = LocalAuthorities.Id.BathAndNorthEastSomerset, Code = "E06000022", Name = "Bath and North East Somerset", RegionId = Regions.Id.SouthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Bedford, Code = "E06000055", Name = "Bedford", RegionId = Regions.Id.EastofEngland },
            new LocalAuthority { Id = LocalAuthorities.Id.Bexley, Code = "E09000004", Name = "Bexley", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Birmingham, Code = "E08000025", Name = "Birmingham", RegionId = Regions.Id.WestMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.BlackburnWithDarwen, Code = "E06000008", Name = "Blackburn with Darwen", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Blackpool, Code = "E06000009", Name = "Blackpool", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Bolton, Code = "E08000001", Name = "Bolton", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.BournemouthChristchurchAndPoole, Code = "E06000058", Name = "Bournemouth, Christchurch & Poole", RegionId = Regions.Id.SouthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.BracknellForest, Code = "E06000036", Name = "Bracknell Forest", RegionId = Regions.Id.SouthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.Bradford, Code = "E08000032", Name = "Bradford", RegionId = Regions.Id.YorkshireandTheHumber },
            new LocalAuthority { Id = LocalAuthorities.Id.Brent, Code = "E09000005", Name = "Brent", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.BrightonAndHove, Code = "E06000043", Name = "Brighton and Hove", RegionId = Regions.Id.SouthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.BristolCityOf, Code = "E06000023", Name = "Bristol, City of", RegionId = Regions.Id.SouthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Bromley, Code = "E09000006", Name = "Bromley", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Buckinghamshire, Code = "E10000002", Name = "Buckinghamshire", RegionId = Regions.Id.SouthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.Bury, Code = "E08000002", Name = "Bury", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Calderdale, Code = "E08000033", Name = "Calderdale", RegionId = Regions.Id.YorkshireandTheHumber },
            new LocalAuthority { Id = LocalAuthorities.Id.Cambridgeshire, Code = "E10000003", Name = "Cambridgeshire", RegionId = Regions.Id.EastofEngland },
            new LocalAuthority { Id = LocalAuthorities.Id.Camden, Code = "E09000007", Name = "Camden", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.CentralBedfordshire, Code = "E06000056", Name = "Central Bedfordshire", RegionId = Regions.Id.EastofEngland },
            new LocalAuthority { Id = LocalAuthorities.Id.CheshireEast, Code = "E06000049", Name = "Cheshire East", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.CheshireWestAndChester, Code = "E06000050", Name = "Cheshire West and Chester", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.CityOfLondon, Code = "E09000001", Name = "City of London", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Cornwall, Code = "E06000052", Name = "Cornwall", RegionId = Regions.Id.SouthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Coventry, Code = "E08000026", Name = "Coventry", RegionId = Regions.Id.WestMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.Croydon, Code = "E09000008", Name = "Croydon", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Cumbria, Code = "E10000006", Name = "Cumbria", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Darlington, Code = "E06000005", Name = "Darlington", RegionId = Regions.Id.NorthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.Derby, Code = "E06000015", Name = "Derby", RegionId = Regions.Id.EastMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.Derbyshire, Code = "E10000007", Name = "Derbyshire", RegionId = Regions.Id.EastMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.Devon, Code = "E10000008", Name = "Devon", RegionId = Regions.Id.SouthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Doncaster, Code = "E08000017", Name = "Doncaster", RegionId = Regions.Id.YorkshireandTheHumber },
            new LocalAuthority { Id = LocalAuthorities.Id.Dorset, Code = "E10000009", Name = "Dorset", RegionId = Regions.Id.SouthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Dudley, Code = "E08000027", Name = "Dudley", RegionId = Regions.Id.WestMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.Durham, Code = "E06000047", Name = "Durham", RegionId = Regions.Id.NorthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.Ealing, Code = "E09000009", Name = "Ealing", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.EastRidingOfYorkshire, Code = "E06000011", Name = "East Riding of Yorkshire", RegionId = Regions.Id.YorkshireandTheHumber },
            new LocalAuthority { Id = LocalAuthorities.Id.EastSussex, Code = "E10000011", Name = "East Sussex", RegionId = Regions.Id.SouthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.Enfield, Code = "E09000010", Name = "Enfield", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Essex, Code = "E10000012", Name = "Essex", RegionId = Regions.Id.EastofEngland },
            new LocalAuthority { Id = LocalAuthorities.Id.Gateshead, Code = "E08000020", Name = "Gateshead", RegionId = Regions.Id.NorthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.Gloucestershire, Code = "E10000013", Name = "Gloucestershire", RegionId = Regions.Id.SouthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Greenwich, Code = "E09000011", Name = "Greenwich", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Hackney, Code = "E09000012", Name = "Hackney", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Halton, Code = "E06000006", Name = "Halton", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.HammersmithAndFulham, Code = "E09000013", Name = "Hammersmith and Fulham", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Hampshire, Code = "E10000014", Name = "Hampshire", RegionId = Regions.Id.SouthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.Haringey, Code = "E09000014", Name = "Haringey", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Harrow, Code = "E09000015", Name = "Harrow", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Hartlepool, Code = "E06000001", Name = "Hartlepool", RegionId = Regions.Id.NorthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.Havering, Code = "E09000016", Name = "Havering", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Herefordshire, Code = "E06000019", Name = "Herefordshire", RegionId = Regions.Id.WestMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.Hertfordshire, Code = "E10000015", Name = "Hertfordshire", RegionId = Regions.Id.EastofEngland },
            new LocalAuthority { Id = LocalAuthorities.Id.Hillingdon, Code = "E09000017", Name = "Hillingdon", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Hounslow, Code = "E09000018", Name = "Hounslow", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.IsleOfWight, Code = "E06000046", Name = "Isle of Wight", RegionId = Regions.Id.SouthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.IslesOfScilly, Code = "E06000053", Name = "Isles of Scilly", RegionId = Regions.Id.SouthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Islington, Code = "E09000019", Name = "Islington", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.KensingtonAndChelsea, Code = "E09000020", Name = "Kensington and Chelsea", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Kent, Code = "E10000016", Name = "Kent", RegionId = Regions.Id.SouthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.KingstonUponHullCityOf, Code = "E06000010", Name = "Kingston upon Hull, City of", RegionId = Regions.Id.YorkshireandTheHumber },
            new LocalAuthority { Id = LocalAuthorities.Id.KingstonUponThames, Code = "E09000021", Name = "Kingston upon Thames", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Kirklees, Code = "E08000034", Name = "Kirklees", RegionId = Regions.Id.YorkshireandTheHumber },
            new LocalAuthority { Id = LocalAuthorities.Id.Knowsley, Code = "E08000011", Name = "Knowsley", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Lambeth, Code = "E09000022", Name = "Lambeth", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Lancashire, Code = "E10000017", Name = "Lancashire", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Leeds, Code = "E08000035", Name = "Leeds", RegionId = Regions.Id.YorkshireandTheHumber },
            new LocalAuthority { Id = LocalAuthorities.Id.Leicester, Code = "E06000016", Name = "Leicester", RegionId = Regions.Id.EastMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.Leicestershire, Code = "E10000018", Name = "Leicestershire", RegionId = Regions.Id.EastMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.Lewisham, Code = "E09000023", Name = "Lewisham", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Lincolnshire, Code = "E10000019", Name = "Lincolnshire", RegionId = Regions.Id.EastMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.Liverpool, Code = "E08000012", Name = "Liverpool", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Luton, Code = "E06000032", Name = "Luton", RegionId = Regions.Id.EastofEngland },
            new LocalAuthority { Id = LocalAuthorities.Id.Manchester, Code = "E08000003", Name = "Manchester", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Medway, Code = "E06000035", Name = "Medway", RegionId = Regions.Id.SouthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.Merton, Code = "E09000024", Name = "Merton", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Middlesbrough, Code = "E06000002", Name = "Middlesbrough", RegionId = Regions.Id.NorthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.MiltonKeynes, Code = "E06000042", Name = "Milton Keynes", RegionId = Regions.Id.SouthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.NewcastleUponTyne, Code = "E08000021", Name = "Newcastle Upon Tyne", RegionId = Regions.Id.NorthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.Newham, Code = "E09000025", Name = "Newham", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Norfolk, Code = "E10000020", Name = "Norfolk", RegionId = Regions.Id.EastofEngland },
            new LocalAuthority { Id = LocalAuthorities.Id.NorthEastLincolnshire, Code = "E06000012", Name = "North East Lincolnshire", RegionId = Regions.Id.YorkshireandTheHumber },
            new LocalAuthority { Id = LocalAuthorities.Id.NorthLincolnshire, Code = "E06000013", Name = "North Lincolnshire", RegionId = Regions.Id.YorkshireandTheHumber },
            new LocalAuthority { Id = LocalAuthorities.Id.NorthSomerset, Code = "E06000024", Name = "North Somerset", RegionId = Regions.Id.SouthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.NorthTyneside, Code = "E08000022", Name = "North Tyneside", RegionId = Regions.Id.NorthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.NorthYorkshire, Code = "E10000023", Name = "North Yorkshire", RegionId = Regions.Id.YorkshireandTheHumber },
            new LocalAuthority { Id = LocalAuthorities.Id.NorthNorthamptonshire, Code = "E06000061", Name = "North Northamptonshire", RegionId = Regions.Id.EastMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.Northumberland, Code = "E06000048", Name = "Northumberland", RegionId = Regions.Id.NorthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.Nottingham, Code = "E06000018", Name = "Nottingham", RegionId = Regions.Id.EastMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.Nottinghamshire, Code = "E10000024", Name = "Nottinghamshire", RegionId = Regions.Id.EastMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.Oldham, Code = "E08000004", Name = "Oldham", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Oxfordshire, Code = "E10000025", Name = "Oxfordshire", RegionId = Regions.Id.SouthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.Peterborough, Code = "E06000031", Name = "Peterborough", RegionId = Regions.Id.EastofEngland },
            new LocalAuthority { Id = LocalAuthorities.Id.Plymouth, Code = "E06000026", Name = "Plymouth", RegionId = Regions.Id.SouthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Portsmouth, Code = "E06000044", Name = "Portsmouth", RegionId = Regions.Id.SouthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.Reading, Code = "E06000038", Name = "Reading", RegionId = Regions.Id.SouthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.Redbridge, Code = "E09000026", Name = "Redbridge", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.RedcarAndCleveland, Code = "E06000003", Name = "Redcar and Cleveland", RegionId = Regions.Id.NorthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.RichmondUponThames, Code = "E09000027", Name = "Richmond upon Thames", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Rochdale, Code = "E08000005", Name = "Rochdale", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Rotherham, Code = "E08000018", Name = "Rotherham", RegionId = Regions.Id.YorkshireandTheHumber },
            new LocalAuthority { Id = LocalAuthorities.Id.Rutland, Code = "E06000017", Name = "Rutland", RegionId = Regions.Id.EastMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.Salford, Code = "E08000006", Name = "Salford", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Sandwell, Code = "E08000028", Name = "Sandwell", RegionId = Regions.Id.WestMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.Sefton, Code = "E08000014", Name = "Sefton", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Sheffield, Code = "E08000019", Name = "Sheffield", RegionId = Regions.Id.YorkshireandTheHumber },
            new LocalAuthority { Id = LocalAuthorities.Id.Shropshire, Code = "E06000051", Name = "Shropshire", RegionId = Regions.Id.WestMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.Slough, Code = "E06000039", Name = "Slough", RegionId = Regions.Id.SouthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.Solihull, Code = "E08000029", Name = "Solihull", RegionId = Regions.Id.WestMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.Somerset, Code = "E10000027", Name = "Somerset", RegionId = Regions.Id.SouthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.SouthGloucestershire, Code = "E06000025", Name = "South Gloucestershire", RegionId = Regions.Id.SouthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.SouthTyneside, Code = "E08000023", Name = "South Tyneside", RegionId = Regions.Id.NorthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.Southampton, Code = "E06000045", Name = "Southampton", RegionId = Regions.Id.SouthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.SouthendOnSea, Code = "E06000033", Name = "Southend-on-Sea", RegionId = Regions.Id.EastofEngland },
            new LocalAuthority { Id = LocalAuthorities.Id.Southwark, Code = "E09000028", Name = "Southwark", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.StHelens, Code = "E08000013", Name = "St. Helens", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Staffordshire, Code = "E10000028", Name = "Staffordshire", RegionId = Regions.Id.WestMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.Stockport, Code = "E08000007", Name = "Stockport", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.StocktonOnTees, Code = "E06000004", Name = "Stockton-on-Tees", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.StokeOnTrent, Code = "E06000021", Name = "Stoke-on-Trent", RegionId = Regions.Id.WestMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.Suffolk, Code = "E10000029", Name = "Suffolk", RegionId = Regions.Id.EastofEngland },
            new LocalAuthority { Id = LocalAuthorities.Id.Sunderland, Code = "E08000024", Name = "Sunderland", RegionId = Regions.Id.NorthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.Surrey, Code = "E10000030", Name = "Surrey", RegionId = Regions.Id.SouthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.Sutton, Code = "E09000029", Name = "Sutton", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Swindon, Code = "E06000030", Name = "Swindon", RegionId = Regions.Id.SouthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Tameside, Code = "E08000008", Name = "Tameside", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.TelfordAndWrekin, Code = "E06000020", Name = "Telford and Wrekin", RegionId = Regions.Id.WestMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.Thurrock, Code = "E06000034", Name = "Thurrock", RegionId = Regions.Id.EastofEngland },
            new LocalAuthority { Id = LocalAuthorities.Id.Torbay, Code = "E06000027", Name = "Torbay", RegionId = Regions.Id.SouthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.TowerHamlets, Code = "E09000030", Name = "Tower Hamlets", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Trafford, Code = "E08000009", Name = "Trafford", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Wakefield, Code = "E08000036", Name = "Wakefield", RegionId = Regions.Id.YorkshireandTheHumber },
            new LocalAuthority { Id = LocalAuthorities.Id.Walsall, Code = "E08000030", Name = "Walsall", RegionId = Regions.Id.WestMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.WalthamForest, Code = "E09000031", Name = "Waltham Forest", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Wandsworth, Code = "E09000032", Name = "Wandsworth", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Warrington, Code = "E06000007", Name = "Warrington", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Warwickshire, Code = "E10000031", Name = "Warwickshire", RegionId = Regions.Id.WestMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.WestBerkshire, Code = "E06000037", Name = "West Berkshire", RegionId = Regions.Id.SouthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.WestNorthamptonshire, Code = "E06000062", Name = "West Northamptonshire", RegionId = Regions.Id.EastMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.WestSussex, Code = "E10000032", Name = "West Sussex", RegionId = Regions.Id.SouthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.Westminster, Code = "E09000033", Name = "Westminster", RegionId = Regions.Id.London },
            new LocalAuthority { Id = LocalAuthorities.Id.Wigan, Code = "E08000010", Name = "Wigan", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Wiltshire, Code = "E06000054", Name = "Wiltshire", RegionId = Regions.Id.SouthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.WindsorAndMaidenhead, Code = "E06000040", Name = "Windsor and Maidenhead", RegionId = Regions.Id.SouthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.Wirral, Code = "E08000015", Name = "Wirral", RegionId = Regions.Id.NorthWest },
            new LocalAuthority { Id = LocalAuthorities.Id.Wokingham, Code = "E06000041", Name = "Wokingham", RegionId = Regions.Id.SouthEast },
            new LocalAuthority { Id = LocalAuthorities.Id.Wolverhampton, Code = "E08000031", Name = "Wolverhampton", RegionId = Regions.Id.WestMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.Worcestershire, Code = "E10000034", Name = "Worcestershire", RegionId = Regions.Id.WestMidlands },
            new LocalAuthority { Id = LocalAuthorities.Id.York, Code = "E06000014", Name = "York", RegionId = Regions.Id.YorkshireandTheHumber }
        );
    }
}