@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define FONTAWESOME_5 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include FONTAWESOME_5/users.puml
!include FONTAWESOME_5/file_excel.puml

Person(schoolStaff, "School Staff", "Member of the school team that has identified a set of pupils with tutoring needs", $sprite="users")
System_Ext(govUkNtp, "GOV.UK National Tutoring programme pages", "Static content explaining the purpose of the programme and the three tutoring options")
System(fatp, "Find a tuition partner", "Search for quality assured Tuition Partners that offer services in a specified location")
System_Ext(academicMentors, "Academic mentors service", "Service supporting option to provide tutoring via academic mentors")
System_Ext(schoolLed, "School-led tutoring", "Service supporting option to provide school-led tutoring")
Person_Ext(tuitionPartners, "Tuition Partners", "Companies that can supply tutors to schools", $sprite="users")
Person_Ext(tpQa, "Tuition Partner Quality Assurance", "Accreditation partner confirming Tuition Partners meet the requirements to be listed on the service", $sprite="users")

Rel_Down(schoolStaff, govUkNtp, "Uses", "HTTPS")
Rel_Down(govUkNtp, fatp, "Uses", "HTTPS")
Rel_Down(govUkNtp, academicMentors, "Uses", "HTTPS")
Rel_Down(govUkNtp, schoolLed, "Uses", "HTTPS")
BiRel_Right(tuitionPartners, tpQa, "Accreditation process") 
Rel_Right(tpQa, fatp, "Suplies data", $sprite="file_excel")

SHOW_LEGEND()
@enduml