@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome
!define FONTAWESOME_5 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/dotnet.puml
!include DEVICONS/postgresql.puml
!include DEVICONS/google_analytics.puml
!include DEVICONS/redis.puml
!include FONTAWESOME/file_text.puml
!include FONTAWESOME_5/users.puml
!include FONTAWESOME_5/cloud.puml
!include FONTAWESOME_5/map_marked.puml
!include FONTAWESOME_5/file_excel.puml
!include FONTAWESOME_5/database.puml
!include FONTAWESOME_5/cloud_upload_alt.puml
!include FONTAWESOME_5/envelope.puml

Person(schoolStaff, "School Staff", "Member of the school team that has identified a set of pupils with tutoring needs", $sprite="users")

Person_Ext(tpQa, "Tuition Partner Quality Assurance", "Accreditation partner confirming Tuition Partners meet the requirements to be listed on the service", $sprite="users")

Person_Ext(tuitionPartner, "Tuition Partner", "Companies that can supply tutors to schools", $sprite="users")
 
Container(azureBlobStorage, "Azure Blob Storage", "TP Data spreadsheets and logos stored within a folder", $sprite="cloud_upload_alt")

System_Boundary(fatp, "Find a tuition partner hosted in GOV.UK Platform as a Service") {
    Container(app, "Web Application", "C#, ASP.NET Core 6.0 Razor Pages", "Search for quality assured Tuition Partners that offer services in a specified location", $sprite="dotnet")
    ContainerDb(db, "Database", "PostgreSQL", "Holds Tuition Partner service coverage and ONS location data", $sprite="postgresql")
    ContainerDb(cache, "Session Cache", "Redis", "Temporary session storage. Primarily to hold un-submitted enquiries and responses.", $sprite="redis")
    Container(dataImporter, "Data Importer", "C#, .NET 6.0 console app", "Decrypts and imports Tuition Partner data files. Run as Cloud Foundry task", $sprite="dotnet")
}

System_Ext(appInsights, "Azure Application Insights", "Application performance monitoring (APM) and Tracing", $sprite="file_text")
System_Ext(googleAnalytics, "Google Analytics", "Opt in metrics collection", $sprite="google_analytics")
System_Ext(postcodesIo, "postcodes.io", "Maps postcode to Local Authority District code", $sprite="map_marked")
System_Ext(bigQuery, "Google BigQuery", "Stores web request data for analytics", $sprite="database")
System_Ext(notify, "GOV.UK Notify", "Send OTPs and other notifications to the user", $sprite="envelope")

Rel(schoolStaff, app, "Uses", "REST API")
Rel(tuitionPartner, app, "Responds to enquiries", "REST API")
Rel(tpQa, azureBlobStorage, "Supplies data via delivery team", "Excel")
Rel_Up(dataImporter, azureBlobStorage, "Read tuition Partner data in Excel format", "REST API")
Rel_Right(app, db, "Read TP Data\nRead/Write Enquiry")
Rel_Left(app, cache, "Store Session")
Rel_Left(dataImporter, db, "Applies migrations, writes Tuition Partner data")
Rel_Down(app, appInsights, "Send log events", "Application Insights")
Rel_Down(app, googleAnalytics, "Send analytics events", "REST API")
Rel_Down(app, postcodesIo, "Query postcode data", "REST API")
Rel_Down(app, bigQuery, "Send analytics events", "REST API")
Rel(app, notify, "Trigger notifications", "REST API")
Rel(notify, schoolStaff, "Enquiry responses", "Email")
Rel(notify, tuitionPartner, "Enquiries", "Email")

SHOW_LEGEND()
@enduml