name: Continuous Deployment to QA Environment

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: .NET Build and Test
    uses: ./.github/workflows/build-and-test.yml

  deploy_to_azure:
    name: Deploy to Azure
    needs: build_and_test
    uses: ./.github/workflows/deploy-to-azure.yml
    with:
      environment: development
      run_database_migrations_and_import_data: true
    secrets: inherit

  e2e-tests:
    name: 'End to End Testing'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [ 1, 2, 3, 4]
    environment: ${{ inputs.environment }}
    needs: [ deploy_to_azure ]
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      - name: End to End Testing
        uses: ./.github/actions/end-to-end-testing
        with:
          az_resource_group_name: ${{ secrets.AZURE_RESOURCE_GROUP  }}
          az_webapp_name: ${{ secrets.AZURE_WEBAPP_NAME }}
          az_tenant_id: ${{ secrets.ARM_TENANT_ID }}
          az_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          az_client_id: ${{ secrets.ARM_CLIENT_ID }}
          az_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}