name: Run Database Migrations and Import Data

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      CF_USERNAME:
        required: true
      CF_PASSWORD:
        required: true
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: development
        type: choice
        options:
          - development
          - research
          - staging
          - production

jobs:
  migrate_import_data:
    name: Migrate Database and Import Data
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    permissions:
      contents: read

    steps:
      - name: Run Database Migration and Data Importer
        uses: ./.github/actions/run-db-migration-and-importer
        with:
          az_resource_group_name: ${{ secrets.AZURE_RESOURCE_GROUP  }}
          az_webapp_name: ${{ secrets.AZURE_WEBAPP_NAME }}
          blob_storage_client_secret: ${{ secrets.BLOB_STORAGE_CLIENT_SECRET }}
          postgresql_server_admin_username: ${{ secrets.POSTGRESQL_SERVER_ADMIN_USERNAME }}
          postgresql_server_admin_password: ${{ secrets.POSTGRESQL_SERVER_ADMIN_PASSWORD }} 
          run_db_migration_and_import_data_on_deployed_app: true