name: Build and Publish Docker Image to GitHub Container Registry

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  build-and-publish-docker-image:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    outputs:
      DOCKER_IMAGE: ${{steps.docker_image.outputs.DOCKER_IMAGE}}

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: set-up-environment
      uses: DFE-Digital/github-actions/set-up-environment@master

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Get Short SHA
      id: sha
      run: |
            echo ::set-output name=short::$(echo $GITHUB_SHA | cut -c -7)

    - name: Set DOCKER_IMAGE environment variable
      id:   docker
      run: |
            if [ "${{github.ref}}" == "refs/heads/main" ]
            then
              echo ::set-output name=DOCKER_IMAGE::${{ env.DOCKER_REPOSITORY }}:sha-${{ steps.sha.outputs.short }}
              echo ::set-output name=DOCKER_EVENT::${{ env.DOCKER_REPOSITORY }}:main
            else
              echo ::set-output name=DOCKER_SHA::${{ env.DOCKER_REPOSITORY }}:sha-${{ steps.sha.outputs.short }}
              echo ::set-output name=DOCKER_IMAGE::${{ env.DOCKER_REPOSITORY }}:review-${{steps.sha.outputs.short }}
              echo ::set-output name=DOCKER_EVENT::${{ env.DOCKER_REPOSITORY }}:PR-${{ github.event.number }}
            fi

    - name: Login to Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push to Github Container Registry
      uses: docker/build-push-action@v3
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: |
          ${{ steps.docker.outputs.DOCKER_IMAGE }}
          ${{ steps.docker.outputs.DOCKER_SHA }}
          ${{ steps.docker.outputs.DOCKER_EVENT }}
        push: true
        build-args: |
          SHA=${{ steps.sha.outputs.short }}
          BUILD_TYPE=release
