name: Build and Publish Docker Image to GitHub Container Registry

on:
  workflow_call:
  push:
    branches-ignore:
      - main

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    outputs:
       image: ${{steps.docker_image.outputs.IMAGE}}
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: set-up-environment
      uses: DFE-Digital/github-actions/set-up-environment@master


    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Get Short SHA
      id: vars
      run: |
             echo ::set-output name=sha_short::$(echo $GITHUB_SHA | cut -c -7)

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
             ${{ runner.os }}-buildx-



    - name: Login to Github Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      uses: docker/build-push-action@v3.0.0
      with:
          push: ${{ github.ref == 'refs/heads/tasks/main' }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: |
                 ${{env.DOCKER_REPOSITORY}}:sha-${{ steps.vars.outputs.sha_short }}

