name: Pull Request Teardown Deployment

on:
  pull_request:
    types: [closed]

concurrency: pr-${{ github.event.number }}

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  TF_VERSION: '~>1.4.5'
  TF_ACTION_WORKING_DIR: './terraform/azure'
  TF_STATE_KEY: 'terraform.tfstate'
    
defaults:
  run:
    shell: bash
    working-directory: ${{ env.TF_ACTION_WORKING_DIR }}

jobs:
  teardown_deployment:
    name: Teardown Deployment
    runs-on: ubuntu-latest
    environment: 'development'

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Install the latest version of the Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false
          
      - name: 'Set TF State Key'
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "TF_STATE_KEY=pr-${{ github.event.pull_request.number }}-terraform.tfstate" >> $GITHUB_ENV
          else
            echo "TF_STATE_KEY=dev-terraform.tfstate" >> $GITHUB_ENV
          fi
          
      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: |
          terraform init -backend-config="resource_group_name=${{ secrets.TF_STATE_RESOURCE_GROUP }}"  \
                         -backend-config="storage_account_name=${{ secrets.TF_STATE_STORAGE_ACCOUNT_NAME }}"  \
                         -backend-config="container_name=${{ secrets.TF_STATE_CONTAINER_NAME }}"  \
                         -backend-config="key=${{ env.TF_ACTION_WORKING_DIR }}/${{ env.TF_STATE_KEY }}" 
          
      - name: 'Terraform Destroy'
        run: |
          terraform destroy -auto-approve
