name: 'Provision FaTP into Azure via Terraform on Pull Request'

on:
  workflow_dispatch:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

concurrency: pr-${{ github.event.number }}


env:
  DOTNET_VERSION: '6.0.x'
  NODE_VERSION: '16'
  APP_CODE_PATH: './UI'
  APP_BASE_URL: ''
  AZURE_WEBAPP_NAME: 'find-a-tp-pr-${{ github.event.number }}'
  AZURE_RESOURCE_GROUP: 's177d01-ntp-pr-${{ github.event.number }}'
  TF_VERSION: '~>1.4.5'
  TF_ACTION_WORKING_DIR: './terraform/azure'
  TF_STATE_KEY: 'terraform.tfstate'
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  TF_VAR_environment: pr-${{ github.event.number }}
  TF_VAR_postgresql_server_admin_username: ${{ secrets.POSTGRESQL_SERVER_ADMIN_USERNAME }}
  TF_VAR_postgresql_server_admin_password: ${{ secrets.POSTGRESQL_SERVER_ADMIN_PASSWORD }}
  TF_VAR_monitor_email_receivers: ${{ secrets.MONITOR_EMAIL_RECEIVERS }}
  TF_VAR_govuk_notify_apikey: ${{ secrets.GOVUK_NOTIFY_APIKEY }}
  TF_VAR_blob_storage_client_secret: ${{ secrets.BLOB_STORAGE_CLIENT_SECRET }}

jobs:    
  terraform-plan:
    name: 'Provision FaTP into Azure via Terraform plan'
    runs-on: ubuntu-latest
    environment: 'development'
    outputs:
      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_ACTION_WORKING_DIR }}

    steps:     
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
      
      # Install the latest version of the Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: 'Set TF State Key'
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "TF_STATE_KEY=pr-${{ github.event.pull_request.number }}-terraform.tfstate" >> $GITHUB_ENV
          else
            echo "TF_STATE_KEY=dev-terraform.tfstate" >> $GITHUB_ENV
          fi

      - name: 'Terraform Init'
        run: |
          terraform init -backend-config="resource_group_name=${{ secrets.TF_STATE_RESOURCE_GROUP }}"  \
                         -backend-config="storage_account_name=${{ secrets.TF_STATE_STORAGE_ACCOUNT_NAME }}"  \
                         -backend-config="container_name=${{ secrets.TF_STATE_CONTAINER_NAME }}"  \
                         -backend-config="key=${{ env.TF_ACTION_WORKING_DIR }}/${{ env.TF_STATE_KEY }}" 
      
      # Checks that all Terraform configuration files adhere to a canonical format
      # Will fail the build if not
      - name: Terraform Format
        run: terraform fmt -check
      
      # Generates an execution plan for Terraform
      # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
      - name: Terraform Plan
        id: tf-plan
        run: |
          export exitcode=0
          terraform plan -var-file="vars-pr.tfvars" -detailed-exitcode -no-color -out tfplan.out || export exitcode=$?
          
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          
          if [ $exitcode -eq 1 ]; then
            echo Terraform Plan Failed!
            exit 1
          else 
            exit 0
          fi
      
      # Save plan to artifacts  
      - name: Publish Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: ${{ env.TF_ACTION_WORKING_DIR }}/tfplan.out
      
      # Create string output of Terraform Plan
      - name: Create String Output
        id: tf-plan-string
        run: |
          TERRAFORM_PLAN=$(terraform show -no-color tfplan.out)
          
          delimiter="$(openssl rand -hex 8)"
          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
          echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo '```terraform' >> $GITHUB_OUTPUT
          echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "</details>" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT
      
      # Publish Terraform Plan as task summary
      - name: Publish Terraform Plan to Task Summary
        env:
          SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
        run: |
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
      
      # If this is a PR post the changes
      - name: Push Terraform Output to PR
        if: github.ref != 'refs/heads/main'
        uses: actions/github-script@v6
        env:
          SUMMARY: "${{ steps.tf-plan-string.outputs.summary }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const body = `${process.env.SUMMARY}`;
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: body
            })
  
  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: 'development'
    needs: [terraform-plan]

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_ACTION_WORKING_DIR }}
    
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Azure CLI Login
        uses: ./.github/actions/azure-login
        with:
          az_tenant_id: ${{ env.ARM_TENANT_ID }}
          az_subscription_id: ${{ env.ARM_SUBSCRIPTION_ID }}
          az_client_id: ${{ env.ARM_CLIENT_ID }}
          az_client_secret: ${{ env.ARM_CLIENT_SECRET }}
          
      - name: Build and publish web app
        uses: ./.github/actions/build-and-publish-app
        with:
          dotnet_version: ${{ env.DOTNET_VERSION }}
          node_version: ${{ env.NODE_VERSION }}
          working_directory: ${{ env.APP_CODE_PATH }}
      
      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false
      
      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: |
          terraform init -backend-config="resource_group_name=${{ secrets.TF_STATE_RESOURCE_GROUP }}"  \
                         -backend-config="storage_account_name=${{ secrets.TF_STATE_STORAGE_ACCOUNT_NAME }}"  \
                         -backend-config="container_name=${{ secrets.TF_STATE_CONTAINER_NAME }}"  \
                         -backend-config="key=${{ env.TF_ACTION_WORKING_DIR }}/${{ env.TF_STATE_KEY }}" 
      
      # Download saved plan from artifacts  
      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: ${{ env.TF_ACTION_WORKING_DIR }}
      
      # Terraform Apply
      - name: Terraform Apply
        run: |
          terraform apply -auto-approve tfplan.out
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.APP_CODE_PATH }}/publish
          
      - name: Run Database Migration and Data Importer
        uses: ./.github/actions/run-db-migration-and-importer
        with:
          az_resource_group_name: ${{ env.AZURE_RESOURCE_GROUP  }}
          az_webapp_name: ${{ env.AZURE_WEBAPP_NAME }}
          blob_storage_client_secret: ${{ env.TF_VAR_blob_storage_client_secret }}
          postgresql_server_admin_username: ${{ env.TF_VAR_postgresql_server_admin_username }}
          postgresql_server_admin_password: ${{ env.TF_VAR_postgresql_server_admin_password }}

      - name: Get Front Door Hostname and Set to APP_BASE_URL
        shell: bash
        run: |
          APP_BASE_URL=$(az afd endpoint show -g ${{ env.AZURE_RESOURCE_GROUP }} --profile-name ${{ env.AZURE_WEBAPP_NAME }}-cdn --endpoint-name ${{ env.AZURE_WEBAPP_NAME }}-cdnendpoint --query "hostName" -o tsv)
          echo "APP_BASE_URL=https://$APP_BASE_URL" >> $GITHUB_ENV
            
      - name: End to End Testing
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./UI
          config: baseUrl="${{ env.APP_BASE_URL }}/",video=false

      - name: Store screenshots on test failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: UI/cypress/screenshots
              