name: Pull Request Teardown Deployment

on:
  pull_request:
    types: [closed]

concurrency: pr-${{ github.event.number }}

jobs:
  teardown_teardown_deployment:
    name: Terraform Teardown Deployment
    uses: ./.github/workflows/terraform-teardown.yml
    with:
      environment: 'development'
      tf_var_environment: 'pr-${{ github.event.number }}'
      tf_var_file_env: 'pr'
      az_webapp_name: 'find-a-tp-pr-${{ github.event.number }}'
      az_resource_group_name: 's177d01-ntp-pr-${{ github.event.number }}'

    secrets:
      az_tenant_id: ${{ secrets.ARM_TENANT_ID }}
      az_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      az_client_id: ${{ secrets.ARM_CLIENT_ID }}
      az_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
      postgresql_server_admin_username: ${{ secrets.POSTGRESQL_SERVER_ADMIN_USERNAME }}
      postgresql_server_admin_password: ${{ secrets.POSTGRESQL_SERVER_ADMIN_PASSWORD }}
      govuk_notify_apikey: ${{ secrets.GOVUK_NOTIFY_APIKEY }}
      blob_storage_client_secret: ${{ secrets.BLOB_STORAGE_CLIENT_SECRET }}
      backend_config_resource_group_name: ${{ secrets.TF_STATE_RESOURCE_GROUP }}
      backend_config_storage_account_name: ${{ secrets.TF_STATE_STORAGE_ACCOUNT_NAME }}
      backend_config_container_name: ${{ secrets.TF_STATE_CONTAINER_NAME }}
